export const CURRENT_WEATHER_STATE_TODAY = 'CURRENT_WEATHER_STATE_TODAY';
export const CURRENT_WEATHER_STATE_THREE_DAYS = 'CURRENT_WEATHER_STATE_THREE_DAYS';
export const CURRENT_WEATHER_STATE_WEEK = 'CURRENT_WEATHER_STATE_WEEK';
export const CURRENT_WEATHER_STATE_TWO_WEEKS = 'CURRENT_WEATHER_STATE_TWO_WEEKS';